[package]
name = "ferrix-model-api"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
ferrix-protos = { path = "../ferrix-protos" }
pyo3 = "0.20.0"
serde = "1.0.188"
thiserror = "1.0.43"
toml = "0.8.2"
